### ISSUE TITLE
fetch should be in try-catch

### ISSUE THREAD

**Issue by iegik** [eventbrite/eventbrite-sdk-javascript#13]
`fetch` should be in try-catch because of possible error on request.
There is no try-catch on https://github.com/eventbrite/eventbrite-sdk-javascript/blob/master/src/request.ts#L42

```
export default (...args) => {
    try {
        return fetch(...args)
    } catch (e) {
        return Promise.reject(e);
    }
};
```

or

```
export default async (...args) => {
    try {
        return await fetch(...args)
    } catch (e) {
        return e;
    }
};
```

https://gist.github.com/iegik/3a69da2034156d52b858096ba3aa26f6

**Comment by benmvp** [comment]
Thanks for the help!

So a timeout in the `fetch` call wouldn't reject the promise?

**Comment by iegik** [comment]
@benmvp Sorry, I can`t reproduce for now, but in some cases I`ve got JS error on fetch execution. Maybe it was ReactNative 54 bug, I don`t remember.
