### ISSUE TITLE
Build Failures on Node v10 & v11

### ISSUE THREAD

**Issue by kwelch** [eventbrite/eventbrite-sdk-javascript#43]
## Current Behavior
Currently, travis is failing for all builds on the `node` host since the latest release (11) came out. 
## Expected Behavior

Build is failing.
## Possible Solution

Upgrade `gulp` and related packages
## Steps to Reproduce (for bugs)

- nvm use 11
- yarn
- yarn build
Note: this errors out but slightly in a different way than travis. mainly due to scripts failing during the install failing. However you get another error in the build references how the modules were build on a different node version.
## Your Environment

* SDK version: 1.0.2
* Node version: v11.0.0
* Browser name and version: N/A
* Operating system: OSX

**Comment by kwelch-eb** [comment]
We have another build failure with this same error. However this time it is on node@10. 

I was able to reproduce locally.
