### ISSUE TITLE
Support full API url in request()

### ISSUE THREAD

**Issue by deremer** [eventbrite/eventbrite-sdk-javascript#47]
At the moment I don't have time to do a PR, but I wanted to share this as it easy enough that your internal team may be able to implement it quickly.

## Current Behavior
The webhooks generated by Eventbrite provide an `api_url` which is a full URL. In order to use this with this SDK, we need to extract that path after `/v3`. This is potentially brittle. 

## Expected Behavior
`.request()` should also support valid full API URLs. Or alternatively, perhaps the webhooks could return something like `api_endpoint`

## Possible Solution
If the url matches the regex `^https://www.eventbriteapi.com/v3/` use the url provided.

I.e., Somewhere around [here](https://github.com/eventbrite/eventbrite-sdk-javascript/blob/41e257a1a46f6d1c2c4a046a2079bcce1175da1a/src/index.ts#L13) do:

```typescript
  let url:string;
  if (urlRegex.test(endpoint)) { 
    url = endpoint;
  } else {
    url = `${baseUrl}${endpoint}`;
  }
```
where `urlRegex` is the valid API url regex to match.

**Comment by benmvp** [comment]
Hi @deremer thanks for the suggestion!

Technically the SDK _does_ support passing a full API url to `request`. You can do so by specifying empty string (`''`) as the `baseUrl`:

```js
const eventbrite = require('eventbrite');

// Create configured Eventbrite SDK
const sdk = eventbrite({
    token: 'OATH_TOKEN_HERE',
    baseUrl: '',
});

const fullUrl = 'https://www.eventbriteapi.com/v3/users/me';

sdk.request(fullUrl).then(res => {
    // handle response data
});
```

Would that work for you?

**Comment by deremer** [comment]
@benmvp Oh great! Yes, that works. 💯  Might I suggest adding that to the README? It's specifically useful to teams also using the webhooks. Thank you for the response.

**Comment by benmvp** [comment]
Glad to help.

That's also a great idea! Done!
