### ISSUE TITLE
Query parameter time_filter ignored

### ISSUE THREAD

**Issue by HughbertD** [eventbrite/eventbrite-sdk-javascript#49]
## Current Behavior

When making a request to: `/users/me/orders/?time_filter=current_future` via the SDK I am receiving _all_ the orders back regardless of the time_filter used

## Expected Behavior

I expect to receive only the `current_future` or `past` events depending on the parameter I provide

## Steps to Reproduce (for bugs)
Generate a token
Provide a request to: `/users/me/orders/?time_filter=current_future`
Observe the orders returned

Provide a request to: `/users/me/orders/?time_filter=past`
Observe the same orders are returned

I then used Insomnia (API client) to make the same request (same token etc) and observed properly filtered events returned depending on the query parameter provided. 

## Your Environment

* SDK version: 1.0.3
* Node version: 8.11.4
* Browser name and version: Chrome 
* Operating system: Mac OS, El Capitan

**Comment by benmvp** [comment]
Hi @HughbertD! 👋🏾

Thanks for your issue. Can you include two things for me?

1. Sample code for how you're making the request
2. A screenshot or other reproduction of the Network tab in your Chrome Developer Tools showing the request be made

This will help us figure out where the breakdown is happening.

**Comment by kwelch** [comment]
I created a [codesandbox that emulates the issue](https://codesandbox.io/s/olyxxrnoq5). I don't see why it would do that, but you can see from the sandbox that is does return 17 items, however when I use the API explorer it only returns 1. 

**Sandbox Result**
![image](https://user-images.githubusercontent.com/1295580/49592309-5f773c00-f936-11e8-94da-7020a8268ecc.png)

**API Explorer**
![image](https://user-images.githubusercontent.com/1295580/49592417-9f3e2380-f936-11e8-99c6-8e3449618701.png)

**Comment by kwelch** [comment]
I debugged this locally with the API. The SDK defaults the `Content-Type` to `application/json`. Within the API parses that `Content-Type` tells it to ignore the query params and use the data or body of the request. 

A workaround is to specifically set the method of the request to `GET`, which skips out defaulting. I have a [sample react app that does this here](https://github.com/kwelch/eb-sdk-example).

I will also open a PR that will default method to `GET`.

**Comment by HughbertD** [comment]
Thanks @kwelch for looking into this, the work around is doing the trick for the time being :) 👍
