### ISSUE TITLE
Expand subcategory doesn't work

### ISSUE THREAD

**Issue by krystian50** [eventbrite/eventbrite-sdk-javascript#74]
## Current Behavior
Request `v3/organizations/${organizationId}/events?time_filter=current_future&status=live&expand=subcategory` returns data with **category** expanded.

## Expected Behavior
Should return data with **subcategory** expanded

It works fine with EventBrite API. The subcategory is expanded.

## Steps to Reproduce (for bugs)
1. Create event with category for organization
2. Use  request `v3/organizations/${organizationId}/events?time_filter=current_future&status=live&expand=subcategory`

## Your Environment
* SDK version: 1.2.2
* Node version: 10
* Browser name and version: none
* Operating system: osx

**Comment by kwelch** [comment]
Hey 👋

I [made this codesandbox](https://codesandbox.io/s/frosty-chandrasekhar-f4str?file=/src/index.js) to reproduce, but I wasn't able to. 

Here is a screenshot when I put in details for my organization event. 

<img width="598" alt="Screen Shot 2020-08-05 at 10 35 43 AM" src="https://user-images.githubusercontent.com/1295580/89433201-a9b25100-d707-11ea-956a-06bc51edf635.png">

Can you give that a try and let me know if it helps?

**Comment by krystian50** [comment]
Hey! You're right. That was my fault. Cache was the reason. Probably `nodemon` kept cache for SDK (weird). Thank you for your time and a super quick answer! 💯
