### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by ronaldh46** [eventbrite/eventbrite-sdk-javascript#86]
I'm have been trying to use the direct v3 api and the SDK, but in both instances I'm getting a CORS error with my requests (`/events/id` and `/users/me`).

Requests work fine in Postman.
I am using node.

`Access to fetch at 'https://www.eventbriteapi.com/v3/users/me' from origin 'http://localhost:3333' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.`

Is there any place where I can add CORS exceptions in Eventbrite?

**Comment by ronaldh46** [comment]
Apologies - realised the API is designed for server to server (was using it in Sanity/NextJS) - will instead create an api route server-side, removing the browser CORS issue.

**Comment by kwelch-eb** [comment]
This is expected to be isomorphic and is actually used within our client side web application to power eventbrite.com. 

I think the issue with this is related to the URL you are attempting to hit. Try adding a trailing `/`, our API is strict about that trailing slash and if it is not there, it will redirect to the URL with the trailing slash. However CORS does not follow redirect which is causing the error you are seeing. 

Sorry for the delay in response on this, but I hope that helps resolve the issue.
